[SQUASH] Merge tag 'android-12.1.0_r7' into staging/lineage-19.1_merge-android-12.1.0_r7
Android 12.1.0 Release 7 (SQ3A.220605.009.A1)

# -----BEGIN PGP SIGNATURE-----
#
# iF0EABECAB0WIQRDQNE1cO+UXoOBCWTorT+BmrEOeAUCYp57OwAKCRDorT+BmrEO
# eC0JAJ9K5QX7NrRSHsX3oP83j3Ygzf7vmQCeKQWcHS/gsIcgaQss62/exKEyz7I=
# =J+LH
# -----END PGP SIGNATURE-----
# gpg: Signature made Tue Jun  7 01:10:03 2022 EEST
# gpg:                using DSA key 4340D13570EF945E83810964E8AD3F819AB10E78
# gpg: Good signature from "The Android Open Source Project <initial-contribution@android.com>" [marginal]
# gpg: initial-contribution@android.com: Verified 1201 signatures in the past
#      7 months.  Encrypted 4 messages in the past 4 months.
# gpg: WARNING: This key is not certified with sufficiently trusted signatures!
# gpg:          It is not certain that the signature belongs to the owner.
# Primary key fingerprint: 4340 D135 70EF 945E 8381  0964 E8AD 3F81 9AB1 0E78

# By Ted Wang (7) and others
# Via Automerger Merge Worker (21) and others
* tag 'android-12.1.0_r7':
  GATT multi read: account for length for variable length read
  Add SDP record for UUID_SERVCLASS_AV_REMOTE_CONTROL when AVRCP startup
  btm: set link policy only for BR/EDR cases
  Increase limit for HID Device Descriptor in BT
  HearingAid: Add the new handle mechanism for audio data is congested
  Fix OOB of L2CAP_CMD_CREDIT_BASED_CONN_RES
  Security fix for potential OOB read in L2CAP
  Security fix for potential OOB read in L2CAP
  Security fix for potential OOB read in L2CAP
  Cert: Introduce GD SL4A combination test infra
  Security fix OOB read due to invalid count in stack/avrc/avrc_pars_ct
  Security fix OOB read due to invalid count in stack/avrc/avrc_pars_ct
  Security fix OOB read due to invalid count in stack/avrc/avrc_pars_ct
  Security fix OOB read due to invalid count in stack/avrc/avrc_pars_ct
  Security fix OOB read due to invalid count in stack/avrc/avrc_pars_ct
  Security fix OOB read due to invalid count in stack/avrc/avrc_pars_ct

Change-Id: I963da10eaaf7580ce2a42fdccb74843434e29472

diff --git a/gd/cert/run b/gd/cert/run
--- a/gd/cert/run
+++ b/gd/cert/run
@@ -89,6 +89,7 @@ NUM_REPETITIONS="1"
 SKIP_SOONG_BUILD=false
 USE_ASHMEM_VENV=true
 VERBOSE_MODE=false
+DEVICE_TEST=false
 
 # Directory for test configs to modify
 CONFIG_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@@ -156,29 +157,7 @@ function parse_options {
         ;;
         --device)
         TEST_CONFIG="${ANDROID_BUILD_TOP}/system/bt/gd/cert/devices_config.json"
-        RR="$(cat ${TEST_CONFIG}|grep \"CERT\\\|DUT\")"
-        if [ "$RR" != "" ]; then
-        DUT_SERIAL="$(menu-adb DUT)"
-        DUT_ADB="adb -s ${DUT_SERIAL}"
-        DUT_NAME="$(adb devices -l | grep -v "List of device" | grep ${DUT_SERIAL} | awk '{ print $6 }' | cut -d ':' -f 2)"
-        CERT_SERIAL="$(menu-adb CERT)"
-        CERT_ADB="adb -s ${CERT_SERIAL}"
-        CERT_NAME="$(adb devices -l | grep -v "List of device" | grep ${CERT_SERIAL} | awk '{ print $6 }' | cut -d ':' -f 2)"
-
-        if [ "${CERT_SERIAL}" == "${DUT_SERIAL}" ]; then
-            echo
-            echo "ERROR: CERT and DUT cannot be the same device, or you only have one device connected!"
-            echo
-            exit 1
-        fi
-
-        ## Set android devices in config
-        pushd .
-        cd "${CONFIG_DIR}"
-        popd
-        sed -i "s/\"DUT\"/\"${DUT_SERIAL}\"/g" ${CONFIG_DIR}/devices_config.json
-        sed -i "s/\"CERT\"/\"${CERT_SERIAL}\"/g" ${CONFIG_DIR}/devices_config.json
-        fi
+        DEVICE_TEST=true
         shift # past argument
         ;;
         # Repeat running the specified test cases by N times in one single setup
@@ -198,6 +177,7 @@ function parse_options {
         BUILD_TARGET=$RUST_BUILD_TARGET
         export RUST_BACKTRACE=1
         TEST_CONFIG=$ANDROID_BUILD_TOP/system/bt/gd/cert/rust_android_devices_config.json
+        DEVICE_TEST=true
         shift # past argument
         ;;
         --rhost)
@@ -235,6 +215,34 @@ function parse_options {
       echo -e "${YELLOW}Try to reuse existing virtualenv at ${CERT_TEST_VENV}${NOCOLOR}"
     fi
 
+}
+
+function select_devices {
+    if [ "$DEVICE_TEST" == true ] ; then
+        RR="$(cat ${TEST_CONFIG}|grep \"CERT\\\|DUT\")"
+        if [ "$RR" != "" ]; then
+            DUT_SERIAL="$(menu-adb DUT)"
+            DUT_ADB="adb -s ${DUT_SERIAL}"
+            DUT_NAME="$(adb devices -l | grep -v "List of device" | grep ${DUT_SERIAL} | awk '{ print $6 }' | cut -d ':' -f 2)"
+            CERT_SERIAL="$(menu-adb CERT)"
+            CERT_ADB="adb -s ${CERT_SERIAL}"
+            CERT_NAME="$(adb devices -l | grep -v "List of device" | grep ${CERT_SERIAL} | awk '{ print $6 }' | cut -d ':' -f 2)"
+
+            if [ "${CERT_SERIAL}" == "${DUT_SERIAL}" ]; then
+                echo
+                echo "ERROR: CERT and DUT cannot be the same device, or you only have one device connected!"
+                echo
+                exit 1
+            fi
+
+            ## Set android devices in config
+            pushd .
+            cd "${CONFIG_DIR}"
+            popd
+            sed -i "s/\"DUT\"/\"${DUT_SERIAL}\"/g" ${TEST_CONFIG}
+            sed -i "s/\"CERT\"/\"${CERT_SERIAL}\"/g" ${TEST_CONFIG}
+        fi
+    fi
 }
 
 function soong_build {
@@ -475,6 +483,7 @@ function menu-adb() {
 function main {
     check_environment
     parse_options $@
+    select_devices
     if [[ "${SKIP_SOONG_BUILD}" != true ]] ; then
         soong_build
     fi
