Cert: Add --verbose mode to dumps logs from subprocesses to STDOUT
* Add "verbose_mode" option in test config JSON
* Add --verbose mode in gd/cert/run script
* In verbose mode, logs from cert stack, stack under test, and
  root-canal will all be dumped to STDOUT with color coded headers
* In implementation, ThreadpoolExecutors were created to run logging
  thread at back-end

Bug: 156038378
Test: gd/cert/run --host --verbose
Tag: #gd-refactor
Change-Id: Id9619775392517b13f60a5108b441c3e6df9ce8f

diff --git a/gd/cert/run b/gd/cert/run
--- a/gd/cert/run
+++ b/gd/cert/run
@@ -23,6 +23,7 @@ TEST_CONFIG="$ANDROID_BUILD_TOP/system/bt/gd/cert/android_devices_config.json"
 TEST_FILTER="-tf $ANDROID_BUILD_TOP/system/bt/gd/cert/all_cert_testcases"
 CLEAN_VENV=false
 NUM_REPETITIONS="1"
+VERBOSE_MODE=false
 
 POSITIONAL=()
 while [[ $# -gt 0 ]]
@@ -54,6 +55,11 @@ case $key in
     # Repeat running the specified test cases by N times in one single setup
     --repeat=*)
     NUM_REPETITIONS="${key#*=}"
+    shift # past argument
+    ;;
+    # This will log everything to both log file and stdout
+    --verbose)
+    VERBOSE_MODE=true
     shift # past argument
     ;;
     *)    # unknown option
@@ -109,6 +115,23 @@ bp3.BaseStruct
 if [[ $? -ne 0 ]] ; then
   echo "Setup failed as bluetooth_packets_python3 cannot be imported"
   exit 1
+fi
+
+if [ "$VERBOSE_MODE" == true ] ; then
+  TEMP_CONFIG=/tmp/temp_acts_config.json
+  cat $TEST_CONFIG | $CERT_TEST_VENV/bin/python -c "
+import sys
+import json
+from acts import keys
+config = json.load(sys.stdin)
+config['verbose_mode'] = True
+print(json.dumps(config))
+  " > $TEMP_CONFIG
+  TEST_CONFIG=$TEMP_CONFIG
+  if [[ $? -ne 0 ]] ; then
+    echo "Setup failed as verbose mode is chosen but cannot be enabled"
+    exit 1
+  fi
 fi
 
 for n in $(seq $NUM_REPETITIONS); do
